### ISSUE TITLE
Compile details of all EMODnet WCS endpoints in `emodnet_wfs()`

### ISSUE THREAD

**Issue by annakrystalli** [EMODnet/EMODnetWCS#1]
Create the equivalent of `emodnet_wfs` tibble of details of EMODnet WCS server information

- [x] Create `emodnet_wcs` tibble
- [ ] Create `emodnet_wcs()` load and caching function

**Comment by salvafern** [comment]
The best compilation is here: https://github.com/EMODnet/Web-Service-Documentation#web-coverage-service-wcs
