### ISSUE TITLE
Draft README

### ISSUE THREAD

**Issue by annakrystalli** [EMODnet/EMODnetWCS#13]

**Comment by annakrystalli** [comment]
@salvafern, I've been modifying content from the EMODnetWFS README. I noticed that this link https://www.emodnet.eu/en/data found [here](https://github.com/EMODnet/EMODnetWFS/blob/d11947c66652fbc8354d932169d1aaa76b079629/README.Rmd#L25) is broken. Any ideas where it should be pointing you for WFS and where for WCS (or will it be the same for both?)

**Comment by salvafern** [comment]
In that link, this https://github.com/EMODnet/Web-Service-Documentation#readme was deployed :) it is broken probably because of the change in the domain.
